services:
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    deploy:
      mode: global
    ports:
      - '12345:8080'  # ingres
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  redis:
    image: redis:latest
    deploy:
      placement:
        constraints:
          - "node.hostname == ubuntu1"
