services:
  swarm-volume-cleanup:
    image: "docker:$CLI_VERSION-cli"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NODE_ID: "{{.Node.ID}}"
    deploy:
      mode: global-job
      restart_policy:
        condition: none
    entrypoint:
      - sh 
      - -c
      - |
        set -xe
        docker volume ls --filter name="$FILTER_NAME" --filter "dangling=true" -q | xargs -r docker volume rm
        echo Done - $$NODE_ID
