services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.role == manager'
          - 'node.hostname == ubuntu1'
    # ports:
    #   - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.role == manager'
          - 'node.hostname == ubuntu1'
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
    external: true
  prometheus_data:
    external: true
